- name: Build Totem Left
        run: west build -s zmk/app -b seeeduino_xiao_ble -d build/left -- -DSHIELD=totem_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Rename Left Artifact
        run: cp build/left/zephyr/zmk.uf2 build/totem_left.uf2

      - name: Build Totem Right
        run: west build -s zmk/app -b seeeduino_xiao_ble -d build/right -- -DSHIELD=totem_right -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"

      - name: Rename Right Artifact
        run: cp build/right/zephyr/zmk.uf2 build/totem_right.uf2

      - name: Archive firmware artifacts
        uses: actions/upload-artifact@v4
        with:
          name: totem-firmware
          path: |
            build/totem_left.uf2
            build/totem_right.uf2
